### ISSUE TITLE
FATAL: The application org.flatpakwine32.Project64/i386/master requires the runtime org.freedesktop.Platform/i386/18.08 which was not found   

### ISSUE THREAD

**Issue by TheSystemGuy1337** [fastrizwaan/Project64_flatpak#1]
This is a showstopper issue. Running the install script crashes the installation, and Flatpak will yell at you saying "mAkE sUrE FlAtpAk iS pRoPeRlY cOnFiGuReD!!"

**Comment by fastrizwaan** [comment]
Try [flatpak-wine](https://github.com/fastrizwaan/flatpak-wine) and see how to use it https://www.youtube.com/watch?v=uEXAsEjaD40 (see download link in the description)

Project64 3.0.1 works fine with flatpak-winezgui.

I've completed Banjo Tooie with 60fps hack with it :-D

**Comment by fastrizwaan** [comment]
You can install project64 3.0.1 using flatpak-wine, using the installer from https://www.pj64-emu.com/download/project64-3-0-1-installer.
